### ISSUE TITLE
Compile neanes as web pages

### ISSUE THREAD

**Issue by efraimkaov** [danielgarthur/neanes-web-app#2]
Is there any possibility to compile [neanes](https://github.com/danielgarthur/neanes) as static web page, to be run standalone whitout **Node.js**?

**Comment by danielgarthur** [comment]
The compiled files in `dist/` would need to be served with a web server. 

The quickest way I know to get the production build up and running locally with an HTTP server would be the following:

In `vue.config.js`, update `publicPath` by removing `/neanes-web-app/`. Then `publicPath` should look like this:

```js
  publicPath:
    process.env.NODE_ENV === 'production' && !process.env.IS_ELECTRON
      ? '/'
      : '/',
```

Then from the root folder of the repo, run `npm run build` followed by `npx http-server dist`. This will use Node.js's [http-server](https://www.npmjs.com/package/http-server) to serve the page.

If you do not want to use Node.js, you would need to use some other web server (IIS, nginx, `python -m http.server`, etc.)
